### ISSUE TITLE
Where can I find saved video using `k4aviewer`

### ISSUE THREAD

**Issue by yu-kuai** [dattalab/azure-acquire#7]
Hi, I have installed all the software on Ubuntu 22.04. I am able to launch the k4aviewer and able to see the live video from camera. However, after I hit stop and save, I cannot find the recorded videos. Could you please share the directory of saved files or is there anything I need to fix?

**Comment by versey-sherry** [comment]
Microsoft only officially supports Ubuntu 18.04 and if you'd like to learn more about where the files are saved, please check out the official documentation: https://learn.microsoft.com/en-us/azure/kinect-dk/record-sensor-streams-file

Please notice that you will need to install all the components in this package to use Azure for acquiring MoSeq
compatible videos and the videos recorded using k4aviewer won't be compatible.
